// Persistence of Vision Ray Tracer Scene Description File
// for FreeCAD (http://www.freecadweb.org)

// Based on examples from the FreeCAD Website and Forum:
// https://forum.freecadweb.org/viewtopic.php?f=36&t=32745

// Modified by Way of wood (www.wayofwood.com)

#version 3.6;

#include "colors.inc"
#include "metals.inc"
#include "woods.inc"
#include "glass.inc"
#include "stones.inc"
#include "rad_def.inc"
#include "textures.inc"

// ----------------------------------------
#declare Rad_Quality = 3;

global_settings {
    assumed_gamma 1.0
    ambient_light color rgb <1.0,1.0,1.0>
    max_trace_level 20

    #switch (Rad_Quality)
     #case (1)
        radiosity { // Settings 1 (fast)
            Rad_Settings(Radiosity_Fast, off, off)
        }
        #break
     #case (2)
        radiosity { // Settings 2 (medium quality)
            Rad_Settings(Radiosity_2Bounce, on, on)
        }
        #break
     #case (3)
        radiosity{ // Settings 3 (high quality)
            Rad_Settings(Radiosity_Final, on, on)
            recursion_limit 2
        }
        #break
    #end
}

// ----------------------------------------

sky_sphere {
  pigment {
    gradient y
    color_map {
      [0.0 color Gray50]
      [0.7 color White]
    }
  }
}

// ----------------------------------------

// Floor
plane {
    y, -1
    texture {
        T_Grnt1
        scale 0.02
    }
    finish { ambient 0.0 reflection 0.1 specular 0.2 }
}


// Standard finish
//#declare StdFinish = F_MetalA;
//#declare StdFinish = finish { diffuse 0.7 };
//#declare StdFinish = finish { phong 0.5 };
//#declare StdFinish = finish { ambient rgb <0.5,0.5,0.5> };
//#declare StdFinish = finish { crand 0.5 phong 0.9};
#declare StdFinish = finish { ambient 0.01 diffuse 0.9 phong 1.0 phong_size 70 metallic brilliance 1.5} ;

// These are textures that can be used:

#declare T_wood = texture {
    T_Wood7
    scale 50.0
    translate x*1
    translate y*10
}

// Other textures are:
// Cherry_Wood, Cork, Dark_Wood, DMFDarkOak, DMFLightOak, DMFWood1
// DMFWood2, DMFWood3, DMFWood4
// See http://texlib.povray.org/wood-browsing_1.html for example pictures


// declares position and view direction

// Generated by FreeCAD (http://www.freecadweb.org/)
#declare cam_location =  <5,25.9077,5>;
#declare cam_look_at  = <5,5,5>;
#declare cam_sky      = <0,0,1>;
#declare cam_angle    = 45; 
camera {
  location  cam_location
  look_at   cam_look_at
  sky       cam_sky
  angle     cam_angle 
  right x*800/600
}
// Written by FreeCAD http://www.freecadweb.org/
// face number1 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box1 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,10,0>,
    <0,10,10>,
    <0,0,10>,
  }
  normal_vectors {
    4,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
  }
  face_indices {
    2,
    <3,2,1>,
    <0,3,1>,
  }
} // end of Face1

// face number2 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box2 = mesh2{
  vertex_vectors {
    4,
    <10,0,0>,
    <10,10,0>,
    <10,10,10>,
    <10,0,10>,
  }
  normal_vectors {
    4,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
  }
  face_indices {
    2,
    <1,2,3>,
    <1,3,0>,
  }
} // end of Face2

// face number3 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box3 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <10,0,0>,
    <10,10,0>,
    <0,10,0>,
  }
  normal_vectors {
    4,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face3

// face number4 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box4 = mesh2{
  vertex_vectors {
    4,
    <0,0,10>,
    <10,0,10>,
    <10,10,10>,
    <0,10,10>,
  }
  normal_vectors {
    4,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face4

// face number5 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box5 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,0,10>,
    <10,0,10>,
    <10,0,0>,
  }
  normal_vectors {
    4,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face5

// face number6 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box6 = mesh2{
  vertex_vectors {
    4,
    <0,10,0>,
    <0,10,10>,
    <10,10,10>,
    <10,10,0>,
  }
  normal_vectors {
    4,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face6



// Declare all together +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box = union {
mesh2{ Pov_Box1}
mesh2{ Pov_Box2}
mesh2{ Pov_Box3}
mesh2{ Pov_Box4}
mesh2{ Pov_Box5}
mesh2{ Pov_Box6}
}
// instance to render
object {Pov_Box
 texture {
      pigment {color rgb <0.8,0.8,0.8>}
      finish {StdFinish } //definition on top of the project
  }
}



// Written by FreeCAD http://www.freecadweb.org/
// face number1 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box1 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,10,0>,
    <0,10,10>,
    <0,0,10>,
  }
  normal_vectors {
    4,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
  }
  face_indices {
    2,
    <3,2,1>,
    <0,3,1>,
  }
} // end of Face1

// face number2 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box2 = mesh2{
  vertex_vectors {
    4,
    <10,0,0>,
    <10,10,0>,
    <10,10,10>,
    <10,0,10>,
  }
  normal_vectors {
    4,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
  }
  face_indices {
    2,
    <1,2,3>,
    <1,3,0>,
  }
} // end of Face2

// face number3 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box3 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <10,0,0>,
    <10,10,0>,
    <0,10,0>,
  }
  normal_vectors {
    4,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face3

// face number4 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box4 = mesh2{
  vertex_vectors {
    4,
    <0,0,10>,
    <10,0,10>,
    <10,10,10>,
    <0,10,10>,
  }
  normal_vectors {
    4,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face4

// face number5 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box5 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,0,10>,
    <10,0,10>,
    <10,0,0>,
  }
  normal_vectors {
    4,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face5

// face number6 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box6 = mesh2{
  vertex_vectors {
    4,
    <0,10,0>,
    <0,10,10>,
    <10,10,10>,
    <10,10,0>,
  }
  normal_vectors {
    4,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face6



// Declare all together +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box = union {
mesh2{ Pov_Box1}
mesh2{ Pov_Box2}
mesh2{ Pov_Box3}
mesh2{ Pov_Box4}
mesh2{ Pov_Box5}
mesh2{ Pov_Box6}
}
// instance to render
object {Pov_Box
 texture {
      pigment {color rgb <0.8,0.8,0.8>}
      finish {StdFinish } //definition on top of the project
  }
}



// Written by FreeCAD http://www.freecadweb.org/
// face number1 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box1 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,10,0>,
    <0,10,10>,
    <0,0,10>,
  }
  normal_vectors {
    4,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
    <-1,0,-0>,
  }
  face_indices {
    2,
    <3,2,1>,
    <0,3,1>,
  }
} // end of Face1

// face number2 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box2 = mesh2{
  vertex_vectors {
    4,
    <10,0,0>,
    <10,10,0>,
    <10,10,10>,
    <10,0,10>,
  }
  normal_vectors {
    4,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
    <1,-0,0>,
  }
  face_indices {
    2,
    <1,2,3>,
    <1,3,0>,
  }
} // end of Face2

// face number3 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box3 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <10,0,0>,
    <10,10,0>,
    <0,10,0>,
  }
  normal_vectors {
    4,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
    <-0,-0,-1>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face3

// face number4 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box4 = mesh2{
  vertex_vectors {
    4,
    <0,0,10>,
    <10,0,10>,
    <10,10,10>,
    <0,10,10>,
  }
  normal_vectors {
    4,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
    <0,0,1>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face4

// face number5 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box5 = mesh2{
  vertex_vectors {
    4,
    <0,0,0>,
    <0,0,10>,
    <10,0,10>,
    <10,0,0>,
  }
  normal_vectors {
    4,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
    <-0,-1,-0>,
  }
  face_indices {
    2,
    <1,0,2>,
    <0,3,2>,
  }
} // end of Face5

// face number6 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box6 = mesh2{
  vertex_vectors {
    4,
    <0,10,0>,
    <0,10,10>,
    <10,10,10>,
    <10,10,0>,
  }
  normal_vectors {
    4,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
    <0,1,0>,
  }
  face_indices {
    2,
    <2,0,1>,
    <2,3,0>,
  }
} // end of Face6



// Declare all together +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#declare Pov_Box = union {
mesh2{ Pov_Box1}
mesh2{ Pov_Box2}
mesh2{ Pov_Box3}
mesh2{ Pov_Box4}
mesh2{ Pov_Box5}
mesh2{ Pov_Box6}
}
// instance to render
object {Pov_Box
 texture {
      pigment {color rgb <0.8,0.8,0.8>}
      finish {StdFinish } //definition on top of the project
  }
}





//default light
light_source {
cam_location + cam_angle * 100
    color White
    area_light <100, 0, 0>, <0, 0, 100>, 20, 20
    adaptive 1
    jitter
    circular orient
    fade_distance 1000 fade_power 2
}

